version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "🤖-Dependabot"
      - "automerge"
      - "dependencies"
      - "security"
      - "security vulnerability"
    commit-message:
      prefix: "(fix) update"
